### ISSUE TITLE
app_process提示Aborted

### ISSUE THREAD

**Issue by Y5neKO** [Torther/DroidCastS#5]
![image](https://github.com/user-attachments/assets/f5f68c37-4f16-472e-88e0-9bbd6c9e1b44)
这样的话是我获取的方式有问题吗

**Comment by Torther** [comment]
替换 $CLASSPATH 为上一条命令返回内容的 package: 后的部分

**Comment by Y5neKO** [comment]
> 替换 $CLASSPATH 为上一条命令返回内容的 package: 后的部分

大佬竟然回复的这么快
![image](https://github.com/user-attachments/assets/195a0711-ea22-4bdf-a667-9691d0a7a74e)
我这边是mumu模拟器，提示没权限，是模拟器问题吗

**Comment by Torther** [comment]
刚刚发现了一处文档错误，改成如下格式就可以了
<img width="752" alt="image" src="https://github.com/user-attachments/assets/d9b7b3ef-2977-4a93-bd6d-f2a9ffa1e130">

**Comment by Y5neKO** [comment]
> 刚刚发现了一处文档错误，改成如下格式就可以了 <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/29655416/369784275-d9b7b3ef-2977-4a93-bd6d-f2a9ffa1e130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzcxOTcsIm5iZiI6MTcyNzA3Njg5NywicGF0aCI6Ii8yOTY1NTQxNi8zNjk3ODQyNzUtZDliN2IzZWYtMjk3Ny00YTkzLWJkNmQtZjJhOWZmYTFlMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYTJiOTc1MDNjMGQyODQ4ZjAzYmE4YTc5NGU3ZmNjNGE1NTI0ZGM2YjQ0NjNiZjJjZDA1NzljODk4NjY5ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LSTDTMs_2jk9DfAvP5zJtnmik3A0Zq0dYwH8iGzWINE">

![image](https://github.com/user-attachments/assets/bb055948-753e-4e2d-ac60-7e444884790b)
好的，这下可以力，感谢大佬
